### ISSUE TITLE
Docker failure

### ISSUE THREAD

**Issue by danieldelijani** [CASP-Systems-BU/GCNSplit#2]
I am experiencing a failure when setting up my docker containers. 

When I run
```docker build -t local-torch-geometric .``` in torch-geometric-docker

I receive the following error:

```
[+] Building 5.1s (35/35) FINISHED                                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 5.95kB                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                     0.6s
 => [ 1/32] FROM docker.io/library/ubuntu:18.04@sha256:ca70a834041dd1bf16cc38dfcd24f0888ec4fa431e09f3344f354cf8d1724499                                             0.0s
 => CACHED [ 2/32] RUN apt-get update && apt-get install -y apt-transport-https ca-certificates &&     rm -rf /var/lib/apt/lists/*                                  0.0s
 => CACHED [ 3/32] RUN apt-get update && apt-get install -y --no-install-recommends apt-utils gnupg2 curl &&     curl -fsSL https://developer.download.nvidia.com/  0.0s
 => CACHED [ 4/32] RUN apt-key del 7fa2af80                                                                                                                         0.0s
 => CACHED [ 5/32] RUN apt-key del 3bf863cc                                                                                                                         0.0s
 => CACHED [ 6/32] RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub                             0.0s
 => CACHED [ 7/32] RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub                             0.0s
 => CACHED [ 8/32] RUN apt-get update && apt-get install                                                                                                            0.0s
 => CACHED [ 9/32] RUN apt-get update && apt-get install -y --no-install-recommends         cuda-cudart-10-1=10.1.243-1         cuda-compat-10-1 &&     ln -s cuda  0.0s
 => CACHED [10/32] RUN apt-get update && apt-get install -y --allow-unauthenticated --no-install-recommends         cuda-libraries-10-1=10.1.243-1         cuda-nv  0.0s
 => CACHED [11/32] RUN apt-get update && apt-get install -y --allow-unauthenticated --no-install-recommends         cuda-libraries-dev-10-1=10.1.243-1         cud  0.0s
 => CACHED [12/32] RUN apt-get update && apt-get install -y --no-install-recommends     libcudnn7=7.6.5.32-1+cuda10.1     libcudnn7-dev=7.6.5.32-1+cuda10.1     &&  0.0s
 => CACHED [13/32] RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf &&     echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf         0.0s
 => CACHED [14/32] RUN rm /etc/apt/sources.list.d/cuda.list &&     rm /etc/apt/sources.list.d/nvidia-ml.list                                                        0.0s
 => CACHED [15/32] RUN apt-get update &&  apt-get install -y     curl     ca-certificates     vim     sudo     git     bzip2     libx11-6  && rm -rf /var/lib/apt/  0.0s
 => CACHED [16/32] RUN mkdir /app                                                                                                                                   0.0s
 => CACHED [17/32] WORKDIR /app                                                                                                                                     0.0s
 => CACHED [18/32] RUN adduser --disabled-password --gecos '' --shell /bin/bash user  && chown -R user:user /app                                                    0.0s
 => CACHED [19/32] RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user                                                                                  0.0s
 => CACHED [20/32] RUN chmod 777 /home/user                                                                                                                         0.0s
 => CACHED [21/32] RUN curl -so ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && chmod +x ~/miniconda.sh  && ~/miniconda.s  0.0s
 => CACHED [22/32] RUN /home/user/miniconda/bin/conda install conda-build  && /home/user/miniconda/bin/conda create -y --name py36 python=3.6.5  && /home/user/min  0.0s
 => CACHED [23/32] RUN conda install -y -c pytorch     cudatoolkit=10.1     "pytorch=1.5.0=py3.6_cuda10.1.243_cudnn7.6.3_0"     torchvision=0.6.0=py36_cu101  && c  0.0s
 => CACHED [24/32] RUN conda install -y h5py=2.8.0  && conda clean -ya                                                                                              0.0s
 => CACHED [25/32] RUN pip install h5py-cache==1.0                                                                                                                  0.0s
 => CACHED [26/32] RUN pip install torchnet==0.0.4                                                                                                                  0.0s
 => CACHED [27/32] RUN conda install -y requests=2.19.1  && conda clean -ya                                                                                         0.0s
 => CACHED [28/32] RUN conda install -y graphviz=2.40.1 python-graphviz=0.8.4  && conda clean -ya                                                                   0.0s
 => CACHED [29/32] RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends     libgtk2.0-0     libcanberra-gtk-module  && sudo rm -rf /var/lib/  0.0s
 => CACHED [30/32] RUN conda install -y -c menpo opencv3=3.1.0  && conda clean -ya                                                                                  0.0s
 => CACHED [31/32] RUN CPATH=/usr/local/cuda/include:$CPATH  && LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64  && DYLD_LIBRA  0.0s
 => ERROR [32/32] RUN pip install torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-sparse==0.6.3 -f ht  4.3s
------                                                                                                                                                                   
 > [32/32] RUN pip install torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-sparse==0.6.3 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-cluster==1.5.4 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-spline-conv==1.2.0 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-geometric:                                                 
#35 1.363 Looking in links: https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html                                                                               
#35 2.027 Collecting torch-scatter==2.0.5                                                                                                                                
#35 2.459   Downloading torch_scatter-2.0.5.tar.gz (20 kB)
#35 4.124     ERROR: Command errored out with exit status 1:
#35 4.124      command: /home/user/miniconda/envs/py36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ue1k1m0l/torch-scatter_0657171b99614dbdb269d3a3fd61126a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ue1k1m0l/torch-scatter_0657171b99614dbdb269d3a3fd61126a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5norrlpi
#35 4.124          cwd: /tmp/pip-install-ue1k1m0l/torch-scatter_0657171b99614dbdb269d3a3fd61126a/
#35 4.124     Complete output (29 lines):
#35 4.124     Traceback (most recent call last):
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2851, in get_entry_map
#35 4.124         ep_map = self._ep_map
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2813, in __getattr__
#35 4.124         raise AttributeError(attr)
#35 4.124     AttributeError: _ep_map
#35 4.124     
#35 4.124     During handling of the above exception, another exception occurred:
#35 4.124     
#35 4.124     Traceback (most recent call last):
#35 4.124       File "<string>", line 1, in <module>
#35 4.124       File "/tmp/pip-install-ue1k1m0l/torch-scatter_0657171b99614dbdb269d3a3fd61126a/setup.py", line 83, in <module>
#35 4.124         packages=find_packages(),
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
#35 4.124         _install_setup_requires(attrs)
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in _install_setup_requires
#35 4.124         dist = MinimalDistribution(attrs)
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 134, in __init__
#35 4.124         distutils.core.Distribution.__init__(self, filtered)
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/setuptools/dist.py", line 451, in __init__
#35 4.124         for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 641, in <genexpr>
#35 4.124         for entry in dist.get_entry_map(group).values()
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2854, in get_entry_map
#35 4.124         self._get_metadata('entry_points.txt'), self
#35 4.124       File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2538, in parse_map
#35 4.124         raise ValueError("Entry points must be listed in groups")
#35 4.124     ValueError: Entry points must be listed in groups
#35 4.124     No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#35 4.124     ----------------------------------------
#35 4.125 WARNING: Discarding https://files.pythonhosted.org/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz#sha256=148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f (from https://pypi.org/simple/torch-scatter/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#35 4.128 ERROR: Could not find a version that satisfies the requirement torch-scatter==2.0.5 (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9)
#35 4.129 ERROR: No matching distribution found for torch-scatter==2.0.5
------
executor failed running [/bin/sh -c pip install torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-sparse==0.6.3 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-cluster==1.5.4 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-spline-conv==1.2.0 -f https://pytorch-geometric.com/whl/torch-torch-1.5.0+cu101.html  && pip install torch-geometric]: exit code: 1
```

I am running this on a Macbook Air with a 1.6 GHz Dual-Core Intel Core i5 CPU and Intel UHD Graphics 617 1536 MB GPU.

**Comment by soniahorchidan** [comment]
Hello! 

Thank you for opening this issue and I am sorry for the inconveniences! I will be looking into this problem soon; in the meantime, please install the dependencies manually and run the code outside the Docker container. I will get back once the problem is solved.

Best regards,
Sonia
